plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.example.krtc_informaction'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.krtc_informaction"
        minSdk 30
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
        buildConfig = true
    }
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
    // RecyclerViewBaseAdapter
    implementation 'io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.2'
    implementation 'io.github.scwang90:refresh-layout-kernel:2.0.6' // 核心庫
    implementation 'io.github.scwang90:refresh-header-classics:2.0.6' // 經典樣式 Header
    implementation 'androidx.cardview:cardview:1.0.0'

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.9.1'

    implementation "io.reactivex.rxjava2:rxandroid:2.0.2"
    implementation "io.reactivex.rxjava2:rxjava:2.2.17"
    implementation "com.squareup.retrofit2:adapter-rxjava2:2.3.0"

    implementation 'com.orhanobut:logger:2.2.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.4'

}